# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tic_tac_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tic_tac_message.proto',
  package='tic_tac_toe',
  serialized_pb=_b('\n\x15tic_tac_message.proto\x12\x0btic_tac_toe\"3\n\x0b\x43oordinates\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\x0e\n\x06symbol\x18\x03 \x02(\t\",\n\x0bGood_choice\x12\x1d\n\x15managed_to_put_symbol\x18\x01 \x02(\x08\"\x1c\n\nPut_symbol\x12\x0e\n\x06symbol\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='tic_tac_toe.Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='tic_tac_toe.Coordinates.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='tic_tac_toe.Coordinates.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='tic_tac_toe.Coordinates.symbol', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=89,
)


_GOOD_CHOICE = _descriptor.Descriptor(
  name='Good_choice',
  full_name='tic_tac_toe.Good_choice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='managed_to_put_symbol', full_name='tic_tac_toe.Good_choice.managed_to_put_symbol', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=135,
)


_PUT_SYMBOL = _descriptor.Descriptor(
  name='Put_symbol',
  full_name='tic_tac_toe.Put_symbol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='tic_tac_toe.Put_symbol.symbol', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.message_types_by_name['Good_choice'] = _GOOD_CHOICE
DESCRIPTOR.message_types_by_name['Put_symbol'] = _PUT_SYMBOL

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATES,
  __module__ = 'tic_tac_message_pb2'
  # @@protoc_insertion_point(class_scope:tic_tac_toe.Coordinates)
  ))
_sym_db.RegisterMessage(Coordinates)

Good_choice = _reflection.GeneratedProtocolMessageType('Good_choice', (_message.Message,), dict(
  DESCRIPTOR = _GOOD_CHOICE,
  __module__ = 'tic_tac_message_pb2'
  # @@protoc_insertion_point(class_scope:tic_tac_toe.Good_choice)
  ))
_sym_db.RegisterMessage(Good_choice)

Put_symbol = _reflection.GeneratedProtocolMessageType('Put_symbol', (_message.Message,), dict(
  DESCRIPTOR = _PUT_SYMBOL,
  __module__ = 'tic_tac_message_pb2'
  # @@protoc_insertion_point(class_scope:tic_tac_toe.Put_symbol)
  ))
_sym_db.RegisterMessage(Put_symbol)


# @@protoc_insertion_point(module_scope)
